### Finngenのダウンロード可能なデータを読み込む

In [2]:
import pandas as pd

In [27]:
df = pd.read_csv("/Users/yoshizawakazuki/Kazuki_module/Genomics/finngen_R12_manifest.tsv",sep="\t")

In [ ]:
# df.to_csv('finngen_R12_manifest.csv')

In [18]:
pd.get_option('display.max_columns')

In [24]:
# # 'display.max_rows' を None に設定
# with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
#     display(df[['phenocode']])

In [8]:
target = df[df['phenocode']=='E4_OVARFAIL']
pd.set_option('display.max_colwidth', None)
print(target['path_https'])

672    https://storage.googleapis.com/finngen-public-data-r12/summary_stats/release/finngen_R12_E4_OVARFAIL.gz
Name: path_https, dtype: object

In [25]:
l = df['phenocode'].unique()
import re

In [26]:
df = pd.read_csv("/Users/yoshizawakazuki/Desktop/Datasets/GWAS_MR_Data/VMSGWAS/VMS_gwas_formatted.tsv.gz", sep="\t")
df.head()

,CHR,BP,SNP,A1,A2,FREQ,BETA,SE,P,N
0,1,10177,rs367896724,AC,A,0.601908,-0.01933,0.01838,0.28,17091110
1,1,10352,rs201106462,TA,T,0.606829,-0.01020,0.01895,0.58,17091110
2,1,10511,rs534229142,A,G,0.998707,-0.04123,0.26300,0.87,17091110
3,1,10616,NaN,C,CCGCCGTTGCAAAGGCGCGCCG,0.005742,-0.01761,0.12223,0.89,17091110
4,1,11008,rs575272151,G,C,0.914498,0.02765,0.03169,0.38,17091110

In [ ]:
# df = pd.read_csv("/Users/yoshizawakazuki/Downloads/finngen_R12_G6_SLEEPAPNO.gz",sep="\t")

/var/folders/6g/w4z9zgn15ng21w8fwdt1bkpr0000gn/T/ipykernel_24992/3913482716.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/yoshizawakazuki/Downloads/finngen_R12_G6_SLEEPAPNO.gz",sep="\t")

In [14]:
df.head()

,#chrom,pos,ref,alt,rsids,nearest_genes,pval,mlogp,beta,sebeta,af_alt,af_alt_cases,af_alt_controls
0,1,13668,G,A,rs2691328,DDX11L1,0.959916,0.017767,-0.003888,0.077369,0.005991,0.005992,0.005991
1,1,14506,G,A,rs1240557819,WASH7P,0.400422,0.397482,-0.070326,0.083635,0.004641,0.004539,0.004654
2,1,14521,C,T,rs1378626194,WASH7P,0.955915,0.019581,0.008889,0.160792,0.001084,0.001079,0.001085
3,1,14717,G,A,rs377122907,WASH7P,0.386871,0.412434,-0.303384,0.350609,0.000237,0.000211,0.000240
4,1,14773,C,T,rs878915777,WASH7P,0.841254,0.075073,-0.009043,0.045152,0.014207,0.014292,0.014196