### 外部CTV-labに取り込むためのSummary Statsの整形

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df_bmi = pd.read_csv(
    "/Users/yoshizawakazuki/Desktop/Datasets/MVMR/GCST90179150_buildGRCh37.tsv",
    sep="\t"
)

In [3]:
df_bmi.head(10)

,variant_id,chromosome,base_pair_location,effect_allele,other_allele,effect_allele_frequency,beta,standard_error,z,p_value
0,rs12238997,1,693731,A,G,0.8807,-0.001050,0.003184,-0.329764,0.741578
1,rs144155419,1,717587,A,G,0.0161,-0.000691,0.008204,-0.084188,0.932907
2,rs148120343,1,730087,T,C,0.9453,0.008446,0.004539,1.860706,0.062786
3,rs141242758,1,734349,T,C,0.8752,-0.000899,0.003123,-0.287957,0.773380
4,rs3115860,1,753405,A,C,0.8608,-0.001500,0.002982,-0.503181,0.614837
5,rs2073813,1,753541,A,G,0.1315,0.000492,0.002872,0.171437,0.863880
6,rs12184325,1,754105,T,C,0.0374,-0.000043,0.005442,-0.007879,0.993713
7,rs3131969,1,754182,A,G,0.1425,0.000966,0.002953,0.327084,0.743604
8,rs3131968,1,754192,A,G,0.1411,0.001479,0.002711,0.545533,0.585387
9,rs3131967,1,754334,T,C,0.1424,0.001009,0.002954,0.341476,0.732746

In [7]:
bmi_mapping={
    'chromosome':'CHR',
    'base_pair_location':'BP',
    'variant_id':'SNP',
    'effect_allele':'A1',
    'other_allele':'A2',
    'effect_allele_frequency':'FREQ',
    'beta':'BETA',
    'standard_error':'SE',
    'p_value':'P'


}

df = df_bmi.rename(columns=bmi_mapping)

In [8]:
df.head()

,SNP,CHR,BP,A1,A2,FREQ,BETA,SE,z,P
0,rs12238997,1,693731,A,G,0.8807,-0.001050,0.003184,-0.329764,0.741578
1,rs144155419,1,717587,A,G,0.0161,-0.000691,0.008204,-0.084188,0.932907
2,rs148120343,1,730087,T,C,0.9453,0.008446,0.004539,1.860706,0.062786
3,rs141242758,1,734349,T,C,0.8752,-0.000899,0.003123,-0.287957,0.773380
4,rs3115860,1,753405,A,C,0.8608,-0.001500,0.002982,-0.503181,0.614837

In [12]:
df.columns

Index(['SNP', 'CHR', 'BP', 'A1', 'A2', 'FREQ', 'BETA', 'SE', 'z', 'P'], dtype='object')

In [13]:
df = df[['SNP', 'CHR', 'BP', 'A1', 'A2', 'FREQ', 'BETA', 'SE', 'P']]
df.head()

           SNP  CHR      BP A1 A2    FREQ      BETA        SE         P
0   rs12238997    1  693731  A  G  0.8807 -0.001050  0.003184  0.741578
1  rs144155419    1  717587  A  G  0.0161 -0.000691  0.008204  0.932907
2  rs148120343    1  730087  T  C  0.9453  0.008446  0.004539  0.062786
3  rs141242758    1  734349  T  C  0.8752 -0.000899  0.003123  0.773380
4    rs3115860    1  753405  A  C  0.8608 -0.001500  0.002982  0.614837

In [14]:
df['N']=len(df)

In [15]:
df

,SNP,CHR,BP,A1,A2,FREQ,BETA,SE,P,N
0,rs12238997,1,693731,A,G,0.8807,-0.001050,0.003184,0.741578,6206408
1,rs144155419,1,717587,A,G,0.0161,-0.000691,0.008204,0.932907,6206408
2,rs148120343,1,730087,T,C,0.9453,0.008446,0.004539,0.062786,6206408
3,rs141242758,1,734349,T,C,0.8752,-0.000899,0.003123,0.773380,6206408
4,rs3115860,1,753405,A,C,0.8608,-0.001500,0.002982,0.614837,6206408
...,...,...,...,...,...,...,...,...,...,...
6206403,rs147475742,22,51219704,A,G,0.0427,-0.000629,0.005105,0.901887,6206408
6206404,rs369304721,22,51221190,A,G,0.0502,0.000655,0.004730,0.889890,6206408
6206405,rs115055839,22,51221731,T,C,0.9268,-0.002757,0.003963,0.486629,6206408
6206406,rs9616985,22,51229805,T,C,0.9251,-0.002682,0.003486,0.441743,6206408
6206407,rs3896457,22,51237063,T,C,0.7072,-0.004030,0.002268,0.075645,6206408

In [ ]:
# gzip圧縮で出力
out_path = "/Users/yoshizawakazuki/Desktop/Datasets/vms_gwas.tsv.gz"

df.to_csv(
    out_path,
    sep="\t",
    index=False,
    compression="gzip"
)