## Two Sample MR用にDataをOrganizeするための関数である：以下実行

In [ ]:
#### UKBiobank由来のSnoringData

In [1]:
import pandas as pd

df_snore = pd.read_csv(
    "/Users/yoshizawakazuki/Desktop/snoring_metal/raw_gwas_stats/Campos_prePMID_Snoring-mainAnalysis.gz",
    sep="\t"
)

In [2]:
df_whr = pd.read_csv(
    "/Users/yoshizawakazuki/Desktop/Datasets/MVMR/fat-distn.giant.ukbb.meta-analysis.whr.combined.tbl.gz",
    sep="\t"
)

In [3]:
df_bmi = pd.read_csv(
    "/Users/yoshizawakazuki/Desktop/Datasets/MVMR/GCST90179150_buildGRCh37.tsv",
    sep="\t"
)

In [4]:
df_snore.head()

   CHR      BP          SNP A1 A2      FREQ      BETA        SE     P
0    1  636285  rs545945172  T  C  0.904303  0.002157  0.002070  0.31
1    1  649192  rs201942322  A  T  0.883020  0.002092  0.001870  0.28
2    1  662414  rs371628865  C  T  0.865541  0.002332  0.001833  0.21
3    1  662622   rs61769339  G  A  0.890009  0.002171  0.001876  0.26
4    1  665266  rs539032812  T  C  0.981032  0.005793  0.004654  0.21

In [5]:
df_bmi.head()

,variant_id,chromosome,base_pair_location,effect_allele,other_allele,effect_allele_frequency,beta,standard_error,z,p_value
0,rs12238997,1,693731,A,G,0.8807,-0.001050,0.003184,-0.329764,0.741578
1,rs144155419,1,717587,A,G,0.0161,-0.000691,0.008204,-0.084188,0.932907
2,rs148120343,1,730087,T,C,0.9453,0.008446,0.004539,1.860706,0.062786
3,rs141242758,1,734349,T,C,0.8752,-0.000899,0.003123,-0.287957,0.773380
4,rs3115860,1,753405,A,C,0.8608,-0.001500,0.002982,-0.503181,0.614837

In [ ]:
# Filter:

## Veteran GWAS - OSA ~ VMS at UKBiobank

In [12]:
df_osa = pd.read_csv(
    "/Users/yoshizawakazuki/Desktop/MR/veteran_osa_associations.tsv",
    sep="\t"
)

In [13]:
df_osa.head()

,varId,alt,ancestry,beta,chromosome,dataset,eaf,maf,multiAllelic,n,...,position,reference,stdErr,unscaled_beta,unscaled_stdErr,zScore,dbSNP,consequence,nearest,minorAllele
0,16:53800954:T:C,C,EU,0.086648,16,Verma2024_MVPTraits_EU,0.4073,0.4073,False,357575.34,...,53800954,T,0.004443,0.086648,0.004443,19.502327,rs1421085,intron_variant,"[""FTO""]",C
1,16:53803223:G:A,A,EU,0.087521,16,Verma2024_MVPTraits_EU,0.4031,0.4031,False,357575.34,...,53803223,G,0.004493,0.087521,0.004493,19.480885,rs62048402,intron_variant,"[""FTO""]",A
2,16:53803574:T:A,A,EU,0.087521,16,Verma2024_MVPTraits_EU,0.4031,0.4031,False,357575.34,...,53803574,T,0.004493,0.087521,0.004493,19.480820,rs1558902,intron_variant,"[""FTO""]",A
3,16:53802494:C:T,T,EU,0.087411,16,Verma2024_MVPTraits_EU,0.4027,0.4027,False,357575.34,...,53802494,C,0.004490,0.087411,0.004490,19.468685,rs11642015,intron_variant,"[""FTO""]",T
4,16:53806453:A:G,G,EU,0.087193,16,Verma2024_MVPTraits_EU,0.4051,0.4051,False,357575.34,...,53806453,A,0.004484,0.087193,0.004484,19.443594,rs56094641,intron_variant,"[""FTO""]",G

In [14]:
df_osa['ancestry'].unique()

array(['EU'], dtype=object)

In [8]:
df_osa.columns

Index(['varId', 'alt', 'ancestry', 'beta', 'chromosome', 'dataset', 'eaf',
       'maf', 'multiAllelic', 'n', 'pValue', 'phenotype', 'position',
       'reference', 'stdErr', 'unscaled_beta', 'unscaled_stdErr', 'zScore',
       'dbSNP', 'consequence', 'nearest', 'minorAllele'],
      dtype='object')

In [9]:
df_osa['pValue']

0      1.049000e-84
1      1.595000e-84
2      1.597000e-84
3      2.024000e-84
4      3.302000e-84
           ...
495    1.339000e-10
496    1.340000e-10
497    1.353000e-10
498    1.354000e-10
499    1.356000e-10
Name: pValue, Length: 500, dtype: float64

In [10]:
"/Users/yoshizawakazuki/Desktop/MR/GCST90267381.tsv.gz"
df_vms = pd.read_csv(
    "/Users/yoshizawakazuki/Desktop/MR/GCST90267381.tsv.gz",
    sep="\t"
)

In [11]:
df_vms.head()

,variant_id,chromosome,base_pair_location,effect_allele,other_allele,effect_allele_frequency,imputation_quality,beta,standard_error,p_value
0,rs367896724,1,10177,A,AC,0.601908,0.467935,-0.01933,0.01838,0.28
1,rs201106462,1,10352,T,TA,0.606829,0.447895,-0.01020,0.01895,0.58
2,rs534229142,1,10511,G,A,0.998707,0.438272,-0.04123,0.26300,0.87
3,NaN,1,10616,CCGCCGTTGCAAAGGCGCGCCG,C,0.005742,0.468098,-0.01761,0.12223,0.89
4,rs575272151,1,11008,C,G,0.914498,0.495023,0.02765,0.03169,0.38